### ISSUE TITLE
Example code compile error in platformio 

### ISSUE THREAD

**Issue by be-engineer** [mcxiaoke/ESPDateTime#3]
When I compile example code in platformio,I got more error messages about datetime.h:

In file included from C:/users/linuxunion/.platformio/lib/ESPDateTime_ID6871/src/ESPDateTime.h:11:0,
                 from D:/develop/project/arduino/ESP32/esp32-cam_webserver2sd/src/esp32cam-Webserver2SD.ino:8:
C:/users/linuxunion/.platformio/lib/ESPDateTime_ID6871/src/DateTime.h: In member function 'int DateTimeParts::getYear() const':
C:/users/linuxunion/.platformio/lib/ESPDateTime_ID6871/src/DateTime.h:49:35: error: invalid use of incomplete type 'const struct tm'
   int getYear() const { return _tm->tm_year + 1900; }
......
What can I do?

**Comment by mcxiaoke** [comment]
using the latest version v1.0.x
