### ISSUE TITLE
Fractional Time Zones

### ISSUE THREAD

**Issue by Bagunceiro** [mcxiaoke/ESPDateTime#9]
It is possible to have time zones with a fraction of an hour - India specifically has a time zone of +5:30. I don't think this is catered for?

**Comment by mcxiaoke** [comment]
Yes, you can, using the latest version, pick TZ name from here: [TZ.h](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/TZ.h) or construct your custom timezone name.
